# -*- coding: utf-8 -*-
"""rag_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IesJYfUgQUtqOti-0nNCk66ku1yAMfpR
"""

!pip install chromadb

!pip install groq

!pip install pypdf

from sentence_transformers import SentenceTransformer
import chromadb
from groq import Groq
import os

import pypdf

pdf_path = "/content/Artificial intelligence - Wikipedia.pdf"   # your file name
txt_path = "/content/ai_wikipedia.txt"

# pdf_path = "/content/Retrieval-augmented generation - Wikipedia.pdf"   # your file name
# txt_path = "/content/rag_wikipedia.txt"

reader = pypdf.PdfReader(pdf_path)

all_text = ""
for page in reader.pages:
    text = page.extract_text()
    if text:
        all_text += text + "\n\n"

with open(txt_path, "w", encoding="utf-8") as f:
    f.write(all_text)

print("Extracted to ai_wikipedia.txt")

# disable tokenizers parallelism to avoid fork warning
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ["GROQ_API_KEY"] = "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"

# initialize embedding model & vector db
print("A) loading embedder...")
# embedder = SentenceTransformer('all-MiniLM-L6-v2')
embedder = SentenceTransformer("msmarco-distilbert-base-v4")
print("Embedder Ready")

from chromadb.config import Settings
import re

def ingest_docs_in_rag(file):

  with open(file, encoding="utf8") as f:
    text = f.read()

  chunks_size = 300 #words
  overlap = 50
  words = text.split()

  text = re.sub(r"\[\d+\]", "", text)            # drop [65] cites
  words = re.sub(r"\s+", " ", text).strip().split()

  chunks = []
  for i in range(0, len(words), chunks_size - overlap):
  # for i in range(0, len(words), chunks_size):
    chunk_words = words[i : i + chunks_size]
    chunk_text = " ".join(chunk_words)
    chunks.append(chunk_text)


  client = chromadb.PersistentClient(path="./db", settings=Settings(anonymized_telemetry=False))
  col = client.get_or_create_collection("research")

  # Add chunks
  for idx, chunk in enumerate(chunks):
      emb = embedder.encode(chunk).tolist()
      col.add(
          ids = [f"wiki_ai_{idx}"],
          documents = [chunk],
          embeddings = [emb],
          metadatas = [{"source":"Wikipedia – Artificial intelligence"}]
      )

  print("Done ingesting Wikipedia article")

# feed documents to rag database
ingest_docs_in_rag("/content/ai_wikipedia.txt")

#
chroma_client = chromadb.PersistentClient(
    path="./db",
    settings=Settings(anonymized_telemetry=False)
)

# create or pull collection
collection = chroma_client.get_collection("research")
# collection = client.get_collection(name="docs")

# initialize groq client
groq_client = Groq()

# conversation loop
conversation_history = []
while True:
    query = input("\nYou: ")
    if query.lower() in ['exit', 'quit', 'q']:
        break

    # rag retrieval
    query_emb = embedder.encode([query]).tolist()

    results = collection.query(query_embeddings=query_emb, n_results=2)
    print("\n Retrieved Chunks:\n")
    for idx, d in enumerate(results["documents"][0]):
        print(f"Chunk {idx+1}:\n{d[:300]}...")  # show first 300 chars
        print("----")


    docs = results.get("documents", [[]])[0]
    context = "\n\n".join(docs) if docs else "(no context found)"
    print("\n[context preview]\n", context[:800], "\n---")

    # build messages and include history
    messages = conversation_history.copy()
    messages.append({
        'role': 'user',
        'content': f'Use the context to answer concisely.\n\nContext:\n{context}\n\nQuestion: {query}'
    })

    response = groq_client.chat.completions.create(
        model = 'llama-3.1-8b-instant',
        messages = messages
    )

    answer = response.choices[0].message.content
    print(f'Bot: {answer}')

    # update history
    conversation_history.append({'role':'user', 'content':query})
    conversation_history.append({'role':'assistant', 'content':answer})

